name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Updated from v3 to v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.5 # Match your local Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Build
        run: flutter build apk --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4 # Updated from v3 to v4
        with:
          name: phonepayui-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
